### PR TITLE
Update CrossDC to Solr 9

### PR DESCRIPTION
**Pull request by sigram**
I think it's time to move on with this code from Solr 8x to Solr 9x.

### CODE REVIEW

**Comment by sigram** [comment]
@markrmiller @anshumg If there are no objections I'd like to merge this next week.

**Comment by HoustonPutman** [comment]
@sigram while we are working on merging to Solr itself, can we not push code here? It's almost impossible to keep them in sync. This one is probably ok, since the same kind of stuff had to be done for the merge, but you'll have to make sure before or after the Solr PR is merged.

**Comment by sigram** [comment]
@HoustonPutman sorry for this complication! my impression was that the other PR wasn't going anywhere soon because of the community pushback. If that's not the case then it's even better.

**Comment by markrmiller** [comment]
I've about to get back to picking up on Houston's current work - I've just about got the tests working.

**Pull request merged**
