### PR TITLE
Shard split supports encryption.

### PR DESCRIPTION
**Pull request by bruno-roustant**

### CODE REVIEW

**Comment by dsmiley** [comment]
I know this is only a "sandbox", but it's disappointing to see a PR proposed and merged inside of an hour with no description or other involvement at all.   It's the Wild West here.  Is this the spirit of the "sandbox" that you proposed @anshumg ?

**Comment by bruno-roustant** [comment]
Oh. I'm glad that you look at this PR, and sorry for being so fast. My previous experience with the PRs waiting in sandbox received no attention.
Please let your remarks and I'll update. And next time I'll wait more.

**Comment by anshumg** [comment]
@dsmiley  - that wasn't the intent, but I see that it was a one off. I guess everyone is on the same page :) Let's respect this repository almost as much as the main one so it's easier for others to collaborate and follow.

**Comment by dsmiley** [comment]
1. communicate (in the description) what this is about.
2. two day standard waiting period before merge.   Another's +1 may accelerate this.

**Pull request merged**
