### PR TITLE
Upgrade Kafka to 3.5.1

### PR DESCRIPTION
**Pull request by sigram**
The project uses version 2.8.1. I propose to upgrade it to a recent version of 3.x (3.5.1) to benefit from many improvements, especially important for the cross-dc mirroring use case (Kafka Connect, MirrorMaker 2, stronger delivery guarantees, etc).

### CODE REVIEW

**Comment by sigram** [comment]
My worry is that Kafka 2.8.1 is already relatively old, and it's a dev line that is purely in maintenance mode - most dev & bugfixing effort goes now to the 3.x line, so it's more future-proof. And since this project is not released yet IMHO it makes sense to follow the recent versions of dependencies.

**Comment by anshumg** [comment]
Do you know if the client is backwards compatible here? I agree we should move to the newer version of Kafka, though would also want to make sure that the users are actually 'on' the new version. If this upgrade is good for both, older version of Kafka and new one, I'm all for it else let's give it some more thought. wdyt ?

**Comment by sigram** [comment]
[This documentation](https://kafka.apache.org/protocol.html#protocol_compatibility) claims it's bi-directionally compatible, ie. old clients can talk with new brokers and old brokers can talk with new clients.

**Comment by sigram** [comment]
If there are no other objections I'd like to merge this soon.

**Comment by markrmiller** [comment]
Tomas has mentioned that he has used. 3.x client against a 2.x cluster.

**Pull request merged**
