### PR TITLE
Add scripts to fetch+prepare solr-community data

### PR DESCRIPTION
**Pull request by gerlowskija**
One common barrier to running performance tests is the lack of a dataset that's ready to be indexed into Solr.  Wikipedia dumps and other public data is common, but there's work needed to massage them into a format that's ready for Solr to index.

This commit partially addresses this problem by introducing scripts that download a dataset and prepare it for indexing into Solr. The output of these scripts is a directory of files that can be indexed with a single `bin/solr post` command.  Hopefully this eliminates at least one of the hurdles in getting a quick perf test running.

The dataset itself is pulled from our community's public interactions. Right now this covers interactions on our mailing lists, and data pulled from Solr's git-log.  Hopefully in the future it can be supplemented with data pulled from JIRA as well.  See
`scripts/community-dataset/README.md` for more details on the dataset and how to use the provided scripts.

### CODE REVIEW

**Comment by epugh** [comment]
I see the `./download-mailing-lists.sh` script runs from the `./scripts` dir, but when I run `./convert-mailing-lists-to-solr-docs.sh $MBOX_OUTPUT_DIR $SOLR_DOC_OUTPUT_DIR` it yells at me about being in the `scripts` sub dir.  

Maybe need...
```
#if [[ "solr-datasets" != $current_dir ]]; then
#  echo "Script intended to be run from the repo root dir; exiting"
#  exit 1
#fi
```

**Comment by epugh** [comment]
I tried to run `bin/post` and got an error...  What is `bin/post`????

**Comment by epugh** [comment]
can we just use a subdir of scripts int he examples and not have to think?

**Comment by epugh** [comment]
I got `maildata` working with a docker image ;-)

**Comment by epugh** [comment]
what does export COLLECTION="maildata" get me?

**Comment by gerlowskija** [comment]
> what does export COLLECTION="maildata" get me?

The shell variable allows users to copy/paste the curl command without modification even if they happened to choose a different collection name.

**Comment by gerlowskija** [comment]
Thanks for the review @epugh.  I addressed most of your comments - defaulting to a local 'output' dir for the scripts to use was a particularly nice improvement 👍 

Let me know if you have any additional thoughts.  Will aim to merge sometime towards the end of this week.

**Review by epugh — APPROVED** [review]
LGTM.    I look forward to the second part, using these in some performance tests ;-)

**Pull request merged**
