### PR TITLE
Straighten out consumer path.

### PR DESCRIPTION
**Pull request by markrmiller**
some general cleanup of course, but specifically, need to remember to add a couple lines to support deletes in serialization.

### CODE REVIEW

**Review by anshumg — COMMENTED** [review]
Seems like there was something with the merge?

- KafkaRequestMirroringHandler.java is deleted, but shouldn't be
- The consumer log files seem to have been added accidentally. Can you please remove them ?

The rest looks fine to merge

**Comment by markrmiller** [comment]
It told me two files (I believe 2) had been removed at origin so I just accepted the remote changes. No idea why if one wasn't removed, but both were orthogonal to anything I did, so should be no problem.

**Comment by anshumg** [comment]
I guess we can close this one out @markrmiller  ?

**Comment by markrmiller** [comment]
Yeah, i started the new PR in case you had pulled this into your work in which case I would have just reconciled them. But as it is I have this in the other PR.

That's a pretty much ready, I've worked through pretty much everything that's come up in manual testing. Just some cleanup and additional testing on it today - i have to rebase it if you have put in any additional changes, but otherwise I'm ready to lock that in and follow up on anything in another.

**Comment by markrmiller** [comment]
Superseded by https://github.com/apache/solr-sandbox/pull/15

**Pull request closed without merging**
